### ISSUE TITLE
eenv:unload/1 slows down the release termination (init:stop/0)

### ISSUE THREAD

**Issue by yhafri** [zhongwencool/erl-env#2]
I've noticed that the call to `eenv:unload(k3)` make my release termination much slower (_3-5 sec_).

```erlang
%% k3_app.erl
-behaviour(application).

-export([start/2, stop/1]).
start(_StartType, _StartArgs) ->
    ok = eenv:load(k3),
    k3_sup:start_link().

stop(_State) ->
    ok = eenv:unload(k3). %% <--- this call make the release stop slower
```

By dropping the call to `eenv:unload(k3)`, the `init:stop()` returns immediately.
Any reason for that? Is it an expected behaviour?

**Comment by zhongwencool** [comment]
Nice catch.
This is because `application_controller` process is block by `init:stop/0`.
But `eenv:unload/1` will call `application_controller` with 5000ms timeout.
so the stop is block about 5000ms.

I can fixed it today. :)

**Comment by zhongwencool** [comment]
please try the latest master.
@yhafri

**Comment by yhafri** [comment]
The `fix` works like charm. Thanks again for your prompt help.
